version: '3.7'
services:
    nextcloud:
        image: nextcloud
        restart: always
        ports:
            - '8080:80'
        volumes:
            - ./nextcloud:/var/www/html
        depends_on:
            - db
    db:
        image: mysql:5.7
        restart: always
        ports:
            - '3306:3306'
        volumes:
            - ./db/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
